# -*- coding: utf-8 -*-
"""organoid_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zemL6wE6GVOAc11HwPeQfKzMU1pSiOpZ

#Organoid Segmentation
"""


#Importing Required Libraries
# If you encounter an ImportError here, especially related to numpy, please restart the Colab runtime.
# Go to 'Runtime' -> 'Restart runtime' and then re-run all cells.
import numpy as np,pandas as pd
import matplotlib.pyplot as plt
import tifffile as tiff
import torch
from cellpose import models
from scipy import ndimage
from skimage import measure
from pathlib import Path
import warnings

warnings.filterwarnings('ignore')

print(f"CUDA Availabilty: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU: None")

#Setting Up Directory Paths
data_dir="/content/drive/MyDrive/Organoid Analysis/images"
nuclei_file=data_dir+"/PDAC-C1.tif"
cells_file=data_dir+"/PDAC-C2.tif"
out_dir=data_dir+"/segmentation_output/"

pix_size_xy=0.345  #µm Per Pixel In XY
pix_size_z=1.0     #µm Per z-Slice
anisotropy=pix_size_z/pix_size_xy

#For Later Use...
slice_view=None
print("Configuration Loaded")
print(f"Anisotropy: {anisotropy:.2f}")

#Loading Images
#Loading Nuclei Channel
print(f"\nLoading: {nuclei_file}")
nuclei=tiff.imread(nuclei_file)
print(f"Nuclei Loaded")
print(f"Shape: {nuclei.shape}")
print(f"Data Type: {nuclei.dtype}")
print(f"Bit Depth: {nuclei.dtype.itemsize*8}-bit")
print(f"Min Value: {nuclei.min()}")
print(f"Max Value: {nuclei.max()}")
print(f"Mean Value: {nuclei.mean():.1f}")

# Load cells channel
print(f"\nLoading: {cells_file}")
cells=tiff.imread(cells_file)
print(f"Cells Loaded")
print(f"Shape: {cells.shape}")
print(f"Data Type: {cells.dtype}")
print(f"Bit Depth: {cells.dtype.itemsize*8}-bit")
print(f"Min Value: {cells.min()}")
print(f"Max Value: {cells.max()}")
print(f"Mean Value: {cells.mean():.1f}")

#Getting Dimensions
z,y,x=nuclei.shape
print(f"\nImage Dimensions: {z} Slices ×{y}×{x} Pixels")
print(f"Physical Size: {z*pix_size_z:.1f}×{y*pix_size_xy:.1f}×{x*pix_size_xy:.1f} μm")

#Determining Which Slice To View
if slice_view is None:
    slc=z//2
    print(f"\nUsing Middle Slice: {slc}")
else:
    slc=slice_view
    print(f"\nUsing Specified Slice: {slc}")

#Visualizing Raw Data
fig,axes=plt.subplots(2,2,figsize=(14,12))

#Nuclei Raw
axes[0,0].imshow(nuclei[slc],cmap='gray',vmin=0,vmax=nuclei.max())
axes[0,0].set_title(f'Nuclei-> Raw (z={slc})',fontsize=13,fontweight='bold')
axes[0,0].axis('off')

#Cells Raw
axes[0,1].imshow(cells[slc],cmap='gray',vmin=0,vmax=cells.max())
axes[0,1].set_title(f'Cells-> Raw (z={slc})',fontsize=13,fontweight='bold')
axes[0,1].axis('off')

#Nuclei Histogram
axes[1,0].hist(nuclei[slc].flatten(),bins=100,color='blue',alpha=0.7,edgecolor='black')
axes[1,0].set_title('Nuclei Intensity Histogram',fontsize=12,fontweight='bold')
axes[1,0].set_xlabel('Intensity')
axes[1,0].set_ylabel('Frequency')
axes[1,0].set_xlim(0,nuclei.max())
axes[1,0].axvline(400,color='red',linestyle='--',label='~400 (Histogram Drop)')
axes[1,0].legend()
axes[1,0].grid(alpha=0.3)

#Cells Histogram
axes[1,1].hist(cells[slc].flatten(),bins=100,color='green',alpha=0.7,edgecolor='black')
axes[1,1].set_title('Cells Intensity Histogram',fontsize=12,fontweight='bold')
axes[1,1].set_xlabel('Intensity')
axes[1,1].set_ylabel('Frequency')
axes[1,1].set_xlim(0,cells.max())
axes[1,1].axvline(1200,color='red',linestyle='--',label='~1200 (Histogram Drop)')
axes[1,1].legend()
axes[1,1].grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("\nObservation: Images Are 16-Bit But Most Information Is In Lower Range")

#Normalizing Images
def normalize_img(img,low=1,high=99):
    p_low=np.percentile(img,low)
    p_high=np.percentile(img,high)

    print(f"Percentile Range: {p_low:.1f}-{p_high:.1f}")

    img_norm=np.clip(img,p_low,p_high)
    img_norm=(img_norm-p_low)/(p_high-p_low+1e-8)
    return img_norm

print("\nNormalizing Nuclei...")
nuclei_norm=normalize_img(nuclei)
print(f"Nuclei Normalized: [{nuclei_norm.min():.3f},{nuclei_norm.max():.3f}]")
print("\nNormalizing Cells...")
cells_norm=normalize_img(cells)
print(f"Cells Normalized: [{cells_norm.min():.3f},{cells_norm.max():.3f}]")

#Visualizing Normalized Data
fig,axes=plt.subplots(1,2,figsize=(14,6))

axes[0].imshow(nuclei_norm[slc],cmap='gray')
axes[0].set_title(f'Nuclei-> Normalized (z={slc})',fontsize=14,fontweight='bold')
axes[0].axis('off')

axes[1].imshow(cells_norm[slc],cmap='gray')
axes[1].set_title(f'Cells-> Normalized (Z={slc})',fontsize=14,fontweight='bold')
axes[1].axis('off')
plt.tight_layout()
plt.show()

#Initializing Cellpose Models For 2D Testing
print("Initializing Cellpose Models (2D Mode)")
use_gpu=torch.cuda.is_available()
print(f"\nUsing GPU: {use_gpu}")

nuclei_diameter=30
nuclei_flow_thres=0.4
nuclei_cprob_thres=0.0
print(f"\nNuclei Parameters:")
print(f"Diameter: {nuclei_diameter} Pixels")
print(f"Flow Threshold: {nuclei_flow_thres}")
print(f"Cellprob Threshold: {nuclei_cprob_thres}")

#Initializing Model
nuclei_mdl2d=models.CellposeModel(gpu=use_gpu,model_type='nuclei')
print("Nuclei Model Loaded: Nuclei")

#Testing Segmentation On 2D Slice: Nuclei
print(f"\nSegmenting Slice {slc}...")
print(f"Parameters:")
print(f"Diameter: {nuclei_diameter} Pixels")
print(f"Flow Threshold: {nuclei_flow_thres}")
print(f"Cellprob Threshold: {nuclei_cprob_thres}")
nuclei_mask2d,nuclei_flow2d=nuclei_mdl2d.eval(
    nuclei_norm[slc],
    diameter=nuclei_diameter,
    channels=[0,0],
    do_3D=False,
    flow_threshold=nuclei_flow_thres,
    cellprob_threshold=nuclei_cprob_thres,
)[:2]
num_nuclei2d=nuclei_mask2d.max()
print(f"\nDetected {num_nuclei2d} Nuclei In Slice {slc}")

#Visualization
fig,axes=plt.subplots(1,3,figsize=(18,6))
axes[0].imshow(nuclei[slc],cmap='gray')
axes[0].set_title(f'Original (z={slc})',fontsize=14,fontweight='bold')
axes[0].axis('off')

axes[1].imshow(nuclei_norm[slc],cmap='gray')
axes[1].imshow(nuclei_mask2d,alpha=0.4,cmap='jet')
axes[1].set_title(f'Segmentation Overlay ({num_nuclei2d} nuclei)',fontsize=14,fontweight='bold')
axes[1].axis('off')

axes[2].imshow(nuclei_mask2d,cmap='tab20')
axes[2].set_title('Masks Only',fontsize=14,fontweight='bold')
axes[2].axis('off')
plt.tight_layout()
plt.show()

#Testing Segmentation On 2D: Cells
cell_diameter=50
cell_flow_thres=0.6
cell_cprob_thres=0

print(f"\nCell Parameters:")
print(f"Diameter: {cell_diameter} Pixels")
print(f"Flow Threshold: {cell_flow_thres}")
print(f"Cellprob Threshold: {cell_cprob_thres}")

#Initializing Models
print("\nLoading Models...")
cell_mdl2d=models.CellposeModel(gpu=use_gpu,model_type='cyto3')
print("Cell Model Loaded: cyto3")

print(f"\nSegmenting slice {slc}...")
print(f"  Parameters:")
print(f"    Diameter: {cell_diameter} pixels")
print(f"    Flow threshold: {cell_flow_thres}")
print(f"    Cellprob threshold: {cell_cprob_thres}")

# Segment single slice in 2D
# Create 2-channel input: [cells, nuclei]
img_2channel = np.stack([cells_norm[slc], nuclei_norm[slc]], axis=-1)

cell_masks_2d, cell_flows_2d = cell_mdl2d.eval(
    img_2channel,
    diameter=cell_diameter,
    channels=[1, 2],  # 1=grayscale cells (channel 0), 2=grayscale nuclei (channel 1)
    do_3D=False,  # 2D mode
    flow_threshold=cell_flow_thres,
    cellprob_threshold=cell_cprob_thres,
)[:2]

num_cells_2d = cell_masks_2d.max()
print(f"\n✓ Detected {num_cells_2d} cells in slice {slc}")

# Visualize with nuclei overlay
fig, axes = plt.subplots(1, 4, figsize=(24, 6))

# Original
axes[0].imshow(cells[slc], cmap='gray')
axes[0].set_title(f'Original Cells (Z={slc})', fontsize=14, fontweight='bold')
axes[0].axis('off')

# Cell segmentation overlay
axes[1].imshow(cells_norm[slc], cmap='gray')
axes[1].imshow(cell_masks_2d, alpha=0.4, cmap='jet')
axes[1].set_title(f'Cell Segmentation ({num_cells_2d} cells)', fontsize=14, fontweight='bold')
axes[1].axis('off')

# Cell masks + nuclei segmentation overlay
axes[2].imshow(cell_masks_2d, cmap='tab20', alpha=0.7)
axes[2].imshow(nuclei_mask2d, alpha=0.5, cmap='Blues')
axes[2].set_title(f'Cells (colored) + Nuclei (blue)', fontsize=14, fontweight='bold')
axes[2].axis('off')

# Cell outlines + nuclei outlines
from skimage import segmentation
cell_outlines = segmentation.find_boundaries(cell_masks_2d, mode='outer')
nuclei_outlines = segmentation.find_boundaries(nuclei_mask2d, mode='outer')

axes[3].imshow(cells_norm[slc], cmap='gray')
axes[3].contour(cell_outlines, colors='red', linewidths=1.5, levels=[0.5])
axes[3].contour(nuclei_outlines, colors='cyan', linewidths=1.5, levels=[0.5])
axes[3].set_title('Outlines: Red=Cells, Cyan=Nuclei', fontsize=14, fontweight='bold')
axes[3].axis('off')

plt.tight_layout()
plt.show()